// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcA9CnTa3aJkw6mwQhUUiieLut157Q0m8',
    appId: '1:668732851913:web:22f89a8a81f9379f11af18',
    messagingSenderId: '668732851913',
    projectId: 'barangayputatan-3d56b',
    authDomain: 'barangayputatan-3d56b.firebaseapp.com',
    storageBucket: 'barangayputatan-3d56b.firebasestorage.app',
    measurementId: 'G-WDSWKZ3D6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJs3IXfrzwqdaiFkYTrfXjanKDj1Z1TDE',
    appId: '1:668732851913:android:4025ba8ed83a71bf11af18',
    messagingSenderId: '668732851913',
    projectId: 'barangayputatan-3d56b',
    storageBucket: 'barangayputatan-3d56b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-NTtkn9zp1Q4WGNpUH_NxrDbZOJxgc8',
    appId: '1:668732851913:ios:f065258d68886e7511af18',
    messagingSenderId: '668732851913',
    projectId: 'barangayputatan-3d56b',
    storageBucket: 'barangayputatan-3d56b.firebasestorage.app',
    iosBundleId: 'com.example.putatanapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-NTtkn9zp1Q4WGNpUH_NxrDbZOJxgc8',
    appId: '1:668732851913:ios:f065258d68886e7511af18',
    messagingSenderId: '668732851913',
    projectId: 'barangayputatan-3d56b',
    storageBucket: 'barangayputatan-3d56b.firebasestorage.app',
    iosBundleId: 'com.example.putatanapk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo1-HmWeCQn_RGmDL7j5-WZTVu5Yj1lzM',
    appId: '1:668732851913:web:1cc610b4a9e9afe511af18',
    messagingSenderId: '668732851913',
    projectId: 'barangayputatan-3d56b',
    authDomain: 'barangayputatan-3d56b.firebaseapp.com',
    storageBucket: 'barangayputatan-3d56b.firebasestorage.app',
    measurementId: 'G-T7ZFMSZTW8',
  );

}